const METHODS=[
['אחוז מתוך שלם','חלק ÷ שלם × 100','אם 30 מתוך 120 — זה 25%.'],
['אחוז שינוי','(חדש פחות ישן) ÷ ישן × 100','תמיד מחלקים בערך הישן.'],
['יחס','מחברים את חלקי היחס, מוצאים ערך של חלק אחד','3:2 = 5 חלקים בסך הכול.'],
['ממוצע','סכום ÷ כמות','חברי את כל הערכים ואז חלקי במספרם.'],
['סדרות','קודם +/−, אחר כך ×/÷, ואז לסירוגין','אל תחפשי חוק מסובך לפני שבדקת חוק פשוט.'],
['תרשימים','קוראים קודם את השאלה ורק אז את הנתונים','כך לא טובעים בטבלה גדולה.'],
['מילולי','מגדירים את הקשר במילים לפני שבוחרים','למשל: "כלי שמשמש ל...".'],
['אנגלית','מבינים את המשפט כולו; לא נתקעים על מילה אחת','חפשי מילות מפתח כמו because, although, by.'],
['אישיות','אין תשובה מושלמת','עני לפי ההתנהגות הרגילה שלך, לא לפי דמות רצויה.'],
['אמינות','כנות, עקביות ושקיפות','המטרה אינה "לשחק את המבחן", אלא לענות באופן מקצועי ואמיתי.']
];
const CALM_MSG=['לירון, קודם להבין מה מבקשים. אחר כך לפתור.','טעות כאן היא מידע — היא מראה מה לתרגל.','מותר לבחור “אני לא יודעת”. אחר כך לומדים את התבנית.','לא צריך להיות מהירה מההתחלה. המהירות מגיעה כשהדפוס מוכר.','שאלה אחת בכל פעם. לא את כל המבחן בבת אחת.'];
const END_MSG=['לירון, היום המטרה הייתה היכרות — לא שלמות.','כל תבנית שזיהית היום תהיה פחות מפתיעה בפעם הבאה.','את לא צריכה לזכור הכול; את צריכה לזהות מה השאלה מבקשת.'];
const KEY='liron-practice-v1';
let store=loadStore(); let session=null; let timerId=null; let pauseId=null;
function loadStore(){try{return JSON.parse(localStorage.getItem(KEY))||{calm:false,mistakes:[],history:[],active:null}}catch(e){return{calm:false,mistakes:[],history:[],active:null}}}
function save(){localStorage.setItem(KEY,JSON.stringify(store))}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function app(){return document.getElementById('app')}
function layout(content){app().className='app'+(store.calm?' calm':'');app().innerHTML=`<div class="wrap"><div class="topbar"><div class="brand">לירון – מתרגלת בנחת</div><div class="top-actions"><button class="btn secondary" onclick="toggleCalm()">${store.calm?'☀ מצב רגיל':'🌿 מצב רגוע'}</button><button class="btn secondary" onclick="openPause()">⏸ עצירה של 30 שניות</button></div></div>${content}<div class="disclaimer">תרגול מקורי לצורכי הכנה בלבד. אינו מבחן רשמי של תיל ואינו משקף בהכרח את מבנה המבחן בפועל.</div></div>`}
function toggleCalm(){store.calm=!store.calm;save(); if(session) renderQuestion(); else home()}
function openPause(){let n=30; const m=document.createElement('div');m.className='modal';m.id='pauseModal';m.innerHTML=`<div class="modal-card"><h2>עוצרים לרגע</h2><p>הניחי את הרגליים על הרצפה, שחררי כתפיים, וקחי נשיפה איטית ונוחה.</p><div class="count" id="count">30</div><p class="muted">אין צורך לעשות שום דבר “מושלם”. רק לעצור.</p><button class="btn" onclick="closePause()">אני מוכנה להמשיך</button></div>`;document.body.appendChild(m);pauseId=setInterval(()=>{n--;const c=document.getElementById('count');if(c)c.textContent=n;if(n<=0)clearInterval(pauseId)},1000)}
function closePause(){clearInterval(pauseId);document.getElementById('pauseModal')?.remove()}
function home(){stopTimer();session=null;const resume=store.active?`<div class="card resume" style="margin-bottom:15px"><h3>יש לך תרגול שלא הסתיים</h3><p class="muted">אפשר להמשיך בדיוק מהמקום שבו עצרת.</p><button class="btn" onclick="resumeSession()">להמשיך</button> <button class="btn link" onclick="clearActive()">לוותר על ההמשך</button></div>`:'';layout(`<section class="hero"><h1>לירון, מתרגלים בנחת</h1><p>המטרה היא להכיר את התבניות, לא להיות מושלמת. כל טעות כאן חוסכת הפתעה במבחן האמיתי.</p><div class="gentle">${CALM_MSG[Math.floor(Math.random()*CALM_MSG.length)]}</div></section>${resume}<div class="grid"><button class="card nav-card" onclick="sectionPicker()"><div class="icon">🧩</div><h3>תרגול לפי נושא</h3><div class="muted">20 שאלות בכל סקשן, עם הסבר מיד אחרי כל תשובה.</div></button><button class="card nav-card" onclick="startShort()"><div class="icon">⚡</div><h3>מבחן קצר</h3><div class="muted">20 שאלות, 4 מכל תחום. יעד: 25 דקות.</div></button><button class="card nav-card" onclick="startLong()"><div class="icon">🧭</div><h3>מבחן ארוך</h3><div class="muted">כל 100 השאלות. אפשר לעצור ולחזור.</div></button><button class="card nav-card" onclick="notebook()"><div class="icon">📘</div><h3>המחברת שלי</h3><div class="muted">הטעויות, ההסברים והתבניות שכדאי לחזק.</div></button><button class="card nav-card" onclick="methods()"><div class="icon">💡</div><h3>מושגים ושיטות</h3><div class="muted">דף עזר קצר: אחוזים, יחס, אנגלית, מילולי ועוד.</div></button><button class="card nav-card" onclick="startMistakes()"><div class="icon">↻</div><h3>רק הטעויות שלי</h3><div class="muted">תרגול ממוקד של שאלות שכבר הכשילו אותי.</div></button></div>`)}
function clearActive(){store.active=null;save();home()}
function sectionPicker(){layout(`<div class="section-head"><div><h2>בחרי נושא</h2><p class="muted">בתרגול לפי נושא מקבלים פידבק מיד אחרי כל שאלה.</p></div><button class="btn secondary" onclick="home()">חזרה</button></div><div class="grid">${Object.entries(S).map(([id,s])=>`<button class="card nav-card" onclick="startPractice('${id}')"><div class="icon">${s.icon}</div><h3>${s.title}</h3><div class="muted">${s.desc}</div><div class="pill" style="margin-top:10px">20 שאלות</div></button>`).join('')}</div>`)}
function makeSession(mode,questions,immediate=false,limitSec=0){return{mode,questions,idx:0,answers:{},immediate,started:Date.now(),elapsed:0,limitSec,feedback:false}}
function startPractice(section){session=makeSession('practice',shuffle(Q[section]),true,0);persistSession();renderQuestion()}
function startShort(){let qs=[];Object.keys(S).forEach(id=>qs.push(...shuffle(Q[id]).slice(0,4)));session=makeSession('short',shuffle(qs),false,25*60);persistSession();renderQuestion();startTimer()}
function startLong(){let qs=[];Object.keys(S).forEach(id=>qs.push(...shuffle(Q[id])));session=makeSession('long',qs,false,180*60);persistSession();renderQuestion();startTimer()}
function startMistakes(){const ids=[...new Set(store.mistakes.filter(x=>!x.mastered).map(x=>x.id))];const all=Object.values(Q).flat();const qs=ids.map(id=>all.find(q=>q.id===id)).filter(Boolean);if(!qs.length){layout(`<div class="card empty"><h2>אין כרגע טעויות פתוחות</h2><p>כשתעני על שאלות, המחברת תאסוף עבורך את מה שכדאי לחזק.</p><button class="btn" onclick="home()">חזרה לבית</button></div>`);return}session=makeSession('mistakes',shuffle(qs),true,0);persistSession();renderQuestion()}
function persistSession(){store.active=session?JSON.parse(JSON.stringify(session)):null;save()}
function resumeSession(){session=store.active;renderQuestion();if(session.limitSec)startTimer()}
function startTimer(){stopTimer();timerId=setInterval(()=>{if(!session)return;session.elapsed=Math.floor((Date.now()-session.started)/1000);const t=document.getElementById('timer');if(t)t.textContent=formatTime(session.elapsed);persistSession()},1000)}
function stopTimer(){if(timerId)clearInterval(timerId);timerId=null}
function formatTime(sec){const m=Math.floor(sec/60),s=sec%60;return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function renderQuestion(){if(!session||session.idx>=session.questions.length){finishSession();return}const q=session.questions[session.idx], s=S[q.section], ans=session.answers[q.id];const p=Math.round((session.idx/session.questions.length)*100);const isPractice=session.immediate;let body='';if(q.kind==='likert'){body=`<div class="likert">${['מאוד לא מסכימה','לא מסכימה','ניטרלי','מסכימה','מאוד מסכימה'].map((x,i)=>`<button class="option ${ans?.value===i+1?'selected':''}" onclick="answerLikert(${i+1})">${i+1}. ${x}</button>`).join('')}</div>`}else{body=`<div class="options">${q.options.map((x,i)=>`<button class="option ${ans?.value===i?'selected':''}" onclick="answerChoice(${i})">${String.fromCharCode(65+i)}. ${x}</button>`).join('')}<button class="option" onclick="answerUnknown()">אני לא יודעת כרגע</button></div>`}
layout(`<div class="section-head"><div><span class="pill">${s.title}</span><h2 style="margin-top:8px">שאלה ${session.idx+1} מתוך ${session.questions.length}</h2></div><div class="row"><span class="timer" id="timer">${formatTime(session.elapsed||0)}</span><button class="btn secondary" onclick="saveAndHome()">שמירה ויציאה</button></div></div><div class="progress"><div style="width:${p}%"></div></div><div class="calm-note">קודם להבין מה מבקשים. אחר כך לבחור דרך פתרון.</div><div class="card"><div class="row between"><span class="pill">${q.patternLabel}</span>${q.difficulty?`<span class="muted">${q.difficulty==='easy'?'קל':q.difficulty==='medium'?'בינוני':'מאתגר'}</span>`:''}</div>${q.context?`<div class="context">${q.context}</div>`:''}<div class="question">${q.prompt}</div>${body}${isPractice&&ans?feedbackHtml(q,ans):''}<div class="quiz-actions"><button class="btn secondary" ${session.idx===0?'disabled':''} onclick="prevQ()">הקודמת</button>${ans&&(!isPractice||session.feedback)?`<button class="btn" onclick="nextQ()">${session.idx===session.questions.length-1?'לסיום':'הבאה'}</button>`:''}${isPractice&&ans&&!session.feedback?`<button class="btn" onclick="showFeedback()">בדיקה והסבר</button>`:''}</div></div>`);if(session.limitSec)startTimer()}
function answerChoice(i){const q=session.questions[session.idx];session.answers[q.id]={value:i,correct:i===q.correctIndex,unknown:false,section:q.section};session.feedback=false;persistSession();if(!session.immediate)nextQ();else renderQuestion()}
function answerUnknown(){const q=session.questions[session.idx];session.answers[q.id]={value:null,correct:false,unknown:true,section:q.section};session.feedback=false;persistSession();if(!session.immediate)nextQ();else renderQuestion()}
function answerLikert(v){const q=session.questions[session.idx];session.answers[q.id]={value:v,correct:null,unknown:false,section:q.section};persistSession();if(!session.immediate)nextQ();else renderQuestion()}
function showFeedback(){session.feedback=true;const q=session.questions[session.idx],ans=session.answers[q.id];recordMistake(q,ans);persistSession();renderQuestion()}
function feedbackHtml(q,ans){if(q.kind==='likert')return `<div class="feedback learn"><h3>אין כאן נכון או לא נכון</h3><p>${q.note}</p><div class="pattern">המפתח: עקביות וכנות.</div></div>`;const ok=ans.correct;return `<div class="feedback ${ok?'':'learn'}"><h3>${ok?'יפה — זיהית את התבנית':'בואי נפרק את זה יחד'}</h3>${ans.unknown?'<p>מצוין שעצרת במקום לנחש. עכשיו לומדים את התבנית.</p>':''}<ol class="steps">${q.explanation.map(x=>`<li>${x}</li>`).join('')}</ol><div class="pattern">תבנית לזכור: ${q.pattern}</div><div class="row" style="margin-top:10px"><button class="btn soft" onclick="toggleSimple('${q.id}')">הסבירי לי אפילו יותר פשוט</button><button class="btn secondary" onclick="similar('${q.id}')">עוד שאלה מאותו סוג</button></div><div id="simple-${q.id}" class="hidden" style="margin-top:12px">${q.simpler}</div></div>`}
function toggleSimple(id){document.getElementById('simple-'+id)?.classList.toggle('hidden')}
function similar(id){const all=Object.values(Q).flat(),cur=all.find(q=>q.id===id);const candidates=all.filter(q=>q.section===cur.section&&q.patternTag===cur.patternTag&&q.id!==id);if(!candidates.length){alert('אין כרגע שאלה נוספת מאותה תבנית בבנק.');return}session.questions.splice(session.idx+1,0,candidates[Math.floor(Math.random()*candidates.length)]);alert('הוספתי לך שאלה דומה מיד אחרי השאלה הנוכחית.');persistSession()}
function recordMistake(q,ans){if(q.kind!=='choice'||ans.correct)return;const exists=store.mistakes.find(x=>x.id===q.id);const obj={id:q.id,section:q.section,prompt:q.prompt,chosen:ans.unknown?'אני לא יודעת':q.options[ans.value],correct:q.options[q.correctIndex],explanation:q.explanation.join(' '),pattern:q.pattern,patternTag:q.patternTag,mastered:false};if(exists)Object.assign(exists,obj);else store.mistakes.push(obj);save()}
function nextQ(){const q=session.questions[session.idx],ans=session.answers[q.id];if(session.immediate&&ans){recordMistake(q,ans)}session.idx++;session.feedback=false;persistSession();renderQuestion()}
function prevQ(){if(session.idx>0){session.idx--;session.feedback=false;persistSession();renderQuestion()}}
function saveAndHome(){persistSession();stopTimer();home()}
function finishSession(){stopTimer();const qs=session.questions,answers=session.answers;qs.forEach(q=>{if(q.kind==='choice'&&answers[q.id])recordMistake(q,answers[q.id])});store.history.push({mode:session.mode,date:new Date().toISOString(),count:qs.length});store.active=null;save();const scored=qs.filter(q=>S[q.section].scored&&q.kind==='choice'),correct=scored.filter(q=>answers[q.id]?.correct).length;const pct=scored.length?Math.round(correct/scored.length*100):null;const by=['quant','verbal','english'].map(id=>{const a=scored.filter(q=>q.section===id);const c=a.filter(q=>answers[q.id]?.correct).length;return{id,n:a.length,p:a.length?Math.round(c/a.length*100):null}});const wrong=qs.filter(q=>q.kind==='choice'&&answers[q.id]&&!answers[q.id].correct);const counts={};wrong.forEach(q=>counts[q.patternLabel]=(counts[q.patternLabel]||0)+1);const top=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,3);const review=qs.filter(q=>q.kind==='choice').map(q=>{const a=answers[q.id];if(!a)return'';return `<details class="card mistake"><summary>${a.correct?'✓':'↻'} ${q.prompt}</summary><p><strong>התשובה שלך:</strong> ${a.unknown?'אני לא יודעת':q.options[a.value]}</p><p><strong>התשובה:</strong> ${q.options[q.correctIndex]}</p><p>${q.explanation.join(' ')}</p><div class="pattern">${q.pattern}</div></details>`}).join('');session=null;layout(`<div class="card scorebox"><h2>סיימת את התרגול</h2>${pct!==null?`<div class="score">${pct}%</div><p class="muted">הציון מתייחס רק לכמותי, מילולי ואנגלית.</p>`:`<p>התרגול הזה אינו מדורג.</p>`}<div class="gentle">${END_MSG[Math.floor(Math.random()*END_MSG.length)]}</div></div>${pct!==null?`<div class="scores">${by.map(x=>`<div class="small-score">${S[x.id].title}<strong>${x.p===null?'—':x.p+'%'}</strong><span class="muted">${x.n} שאלות</span></div>`).join('')}</div>`:''}<div class="card" style="margin:15px 0"><h3>נושאים שכדאי לחזק</h3>${top.length?top.map(x=>`<div class="pill" style="margin:4px">${x[0]} · ${x[1]}</div>`).join(''):'<p class="muted">אין כרגע דפוס חוזר של טעויות.</p>'}<div class="row" style="margin-top:14px"><button class="btn" onclick="startMistakes()">תרגלי רק את הטעויות שלי</button><button class="btn secondary" onclick="home()">חזרה לבית</button></div></div><h2 style="margin-top:26px">סקירת תשובות</h2>${review}`)}
function notebook(filter='all'){const items=store.mistakes.filter(x=>filter==='all'||x.section===filter);layout(`<div class="section-head"><div><h2>המחברת שלי</h2><p class="muted">כאן נשמרות טעויות כדי להפוך אותן לתבניות מוכרות.</p></div><button class="btn secondary" onclick="home()">חזרה</button></div><div class="tabs"><button class="tab ${filter==='all'?'active':''}" onclick="notebook('all')">הכול</button>${Object.entries(S).filter(([id])=>id!=='personality').map(([id,s])=>`<button class="tab ${filter===id?'active':''}" onclick="notebook('${id}')">${s.title}</button>`).join('')}</div>${items.length?items.map((m,i)=>`<details class="card mistake"><summary>${m.mastered?'✓ הבנתי · ':''}${m.prompt}</summary><p><strong>עניתי:</strong> ${m.chosen}</p><p><strong>התשובה:</strong> ${m.correct}</p><p>${m.explanation}</p><div class="pattern">${m.pattern}</div><button class="btn soft" onclick="master('${m.id}','${filter}')">${m.mastered?'להחזיר לחיזוק':'סימנתי: הבנתי'}</button></details>`).join(''):`<div class="card empty">עוד אין כאן פריטים. זה בסדר — המחברת תיבנה תוך כדי תרגול.</div>`}`)}
function master(id,filter){const m=store.mistakes.find(x=>x.id===id);if(m)m.mastered=!m.mastered;save();notebook(filter)}
function methods(){layout(`<div class="section-head"><div><h2>מושגים ושיטות</h2><p class="muted">דף עזר קצר. לא צריך לשנן הכול — מספיק לזהות איזו תבנית מתאימה.</p></div><button class="btn secondary" onclick="home()">חזרה</button></div><div class="grid">${METHODS.map((m,i)=>`<div class="card method"><div class="num">${i+1}</div><div><h3>${m[0]}</h3><p><strong>${m[1]}</strong></p><p class="muted">${m[2]}</p></div></div>`).join('')}</div>`)}
window.addEventListener('beforeunload',()=>{if(session)persistSession()});
home();